import { lazy } from 'react';

export const Main = lazy(() => import('./Main'));
export const Login = lazy(() => import('./Login'));
export const Community = lazy(() => import('./CardList'));
export const NewPost = lazy(() => import('./NewPost'));
export const MyPage = lazy(() => import('./MyPage'));
export const CardList = lazy(() => import('./CardList'));
export const CardDetail = lazy(() => import('./CardDetail'));
export const QnaAnswer = lazy(() => import('./QnaAnswer'));
export const AuthExpert = lazy(() => import('./AuthExpert'));
export const Signup = lazy(() => import('./Signup'));
export const PetProfile = lazy(() => import('./PetProfile'));
export const PetProfileEditor = lazy(() => import('./PetProfileEditor'));
export const ExpertProfile = lazy(() => import('./ExpertProfile'));
export const ExpertProfileEditor = lazy(() => import('./ExpertProfileEditor'));
export const MyActivityInfo = lazy(() => import('./MyActivityInfo'));
export const MyProfileEditor = lazy(() => import('./MyProfileEditor'));
export const KakaoLogin = lazy(() => import('./Login/Kakao'));
export const Account = lazy(() => import('./MyPage/Account'));
